### ISSUE TITLE
Problem processing Movies; unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by kesm** [chazlarson/Media-Scripts#19]
Hello, 
I'm trying to make an export of my movies to retrieve the tmdb ids so I created a dynamic collection with all my movies and run list-item-ids.py but I have an error on this movie "Aya et la sorcière", or maybe the next one: "Aymeric Lompret : Tant Pis". I'm not sure what part is missing in the metadata, but it looks complete on Plex side

```
on 3: Collection: Movies item    73/ 1032 | TMDb ID:  683127    | IMDb ID: tt12441478  | Aya et la sorcière
Grab Collection details |████████████████████████⚠︎               | (!) 3/5 [60%] in 43.7s (0.07/s) 
Problem processing Movies; unsupported format string passed to NoneType.__format__
```

**Comment by chazlarson** [comment]
I wasn't accounting for blank IDs; this has been fixed.
