### ISSUE TITLE
extract_collections.py error when writing the yaml file

### ISSUE THREAD

**Issue by BRAYDIN72** [chazlarson/Media-Scripts#20]
File "/mnt/user/Media-Scripts/Plex-Meta-Manager/extract_collections.py", line 99, in <module>
    yaml.round_trip_dump(
  File "/usr/lib64/python3.9/site-packages/ruamel/yaml/main.py", line 1284, in round_trip_dump
    error_deprecation('round_trip_dump', 'dump')
  File "/usr/lib64/python3.9/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"round_trip_dump()" has been removed, use

  yaml = YAML()
  yaml.dump(...)

instead of file "/mnt/user/Media-Scripts/Plex-Meta-Manager/extract_collections.py", line 99

    yaml.round_trip_dump(

**Comment by BRAYDIN72** [comment]
Running it on Unraid with the Python 3 package installed.
Here is pip freeze output 

about-time==3.1.1
alive-progress==2.4.1
certifi==2023.11.17
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
cinemagoer==2023.5.1
cryptography==41.0.7
distlib==0.3.8
filelock==3.13.1
filetype==1.2.0
grapheme==0.6.0
greenlet==3.0.3
identify==2.5.33
idna==3.6
IMDbPY==2022.7.9
lxml==4.9.4
nodeenv==1.8.0
pathvalidate==3.2.0
piexif==1.1.3
platformdirs==4.1.0
PlexAPI==4.15.7
pre-commit==3.6.0
pycparser==2.21
pyOpenSSL==23.3.0
python-dotenv==1.0.0
PyYAML==6.0.1
requests==2.31.0
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
SQLAlchemy==1.4.50
tabulate==0.9.0
tmdbapis==1.2.2
tmdbsimple==2.9.1
tmdbv3api==1.9.0
tvdb-v4-official==1.1.0
urllib3==2.1.0
validators==0.22.0
virtualenv==20.25.0****

**Comment by chazlarson** [comment]
I added some updated code around the YAML write to try to avoid this.

**Comment by BRAYDIN72** [comment]
Now this error File

 "/mnt/user/Media-Scripts/Plex-Meta-Manager/extract_collections.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by BRAYDIN72** [comment]
New error 

Traceback (most recent call last):
  File "/mnt/user/Media-Scripts/Plex-Meta-Manager/extract_collections.py", line 8, in <module>
    from logs import setup_logger, plogger, blogger, logger
ModuleNotFoundError: No module named 'logs'

**Comment by chazlarson** [comment]
Ah, shoot.  Copy logs.py over from the Plex directory.

**Comment by chazlarson** [comment]
@BRAYDIN72  Anything further needed here?

**Comment by BRAYDIN72** [comment]
Sorry. No this worked, thanks!
