### ISSUE TITLE
Image_picker.py UI enhancement

### ISSUE THREAD

**Issue by bullmoose20** [chazlarson/Media-Scripts#29]
Navigation links need more space allowing people to more easily click on previous or next.

Right justify "next"

Left justify "previous"
![image](https://github.com/chazlarson/Media-Scripts/assets/12549033/2ece0763-711b-4195-9b37-da304060964f)

**Comment by chazlarson** [comment]
![image](https://github.com/chazlarson/Media-Scripts/assets/3865541/f4920c3d-9304-4035-817d-3af8e4d22d39)
