### ISSUE TITLE
Grab Current Poster isn't working for me

### ISSUE THREAD

**Issue by dagov765** [chazlarson/Media-Scripts#4]
When I run grab current poster it seems to be grabbing the background image instead of the actual poster. Sorry if this is not the right place to put this I am new to github.

**Comment by dagov765** [comment]
Ahh understood my apologies if I'd missed that statement on the main page. Most of my reason for wanting to have it is that my in-laws internet is hot garbage so it'd be nice to have the files offline and use meta manager to just set the posters. Their plex server is basically just a clone of mine that I transfer stuff to using an external hard drive.

**Comment by chazlarson** [comment]
If you run grab-all-posters with the depth set to 1 it may grab the current poster; I can't recall how plex orders them.

**Comment by chazlarson** [comment]
grab-all-posters has been updated with a flag to grab the current artwork.
