### ISSUE TITLE
Problem processing Movies; PlexServer.search() got an unexpected keyword argument 'libtype'

### ISSUE THREAD

**Issue by Aabayoumy** [chazlarson/Media-Scripts#40]
error 
what i miss hear?

**Comment by Aabayoumy** [comment]
python3 grab-all-IDs.py
Starting grab-all-IDs
connecting to http://10.0.0.10:32400...
/home/abayoumy/tools/Media-Scripts/Plex/grab-all-IDs.py:82: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  ids = db.Table('keys', metadata, autoload=True, autoload_with=engine)
getting 288 movies from [Movies]...
Problem processing Movies; PlexServer.search() got an unexpected keyword argument 'libtype'
getting 76 shows from [TV Shows]...
Problem processing TV Shows; PlexServer.search() got an unexpected keyword argument 'libtype'
NEW: 0; UPDATED: 0

**Comment by chazlarson** [comment]
There was some refactoring done which wasn't accounted for in this script.

The sqlalchemy warning may still appear, but that's just a warning.  I have added env vars to attempt to disable those warnings.

[10563b6](https://github.com/chazlarson/Media-Scripts/commit/10563b607e1822fbd7b680cf78ce1c68f9d6b5ab)
