### ISSUE TITLE
using reset-posters-plex.py

### ISSUE THREAD

**Issue by pazport** [chazlarson/Media-Scripts#9]
i have been having problems with my posters not loading. started using this today and so far it is working great. i can see posters now loading fine. there is 1 error i keep seeing. and i don't see any explanation for it. 
```on 7864: Exception processing "Lost Pyramids of the Aztecs"
on 8022: Exception processing "Love Is a Rhombus"
on 8224: Exception processing "Lucy Worsley's Royal Palace Secrets"
on 8322: Exception processing "Macy's 4th of July Fireworks Spectacular"
on 8385: Exception processing "Madeleine McCann: The Hunt for the Prime Suspect"
on 8410: Exception processing "Maestro"```
what would be causing this mate

**Comment by chazlarson** [comment]
Most likely this would mean that Plex doesn't have any art for those shows.

The script is getting the list of posters from Plex and just picking the first one, and I didn't have error handling in there for the case of an empty list.

I've added that just now along with printing the actual exception in that message above.

**Comment by Man12340** [comment]
ye i thought as much mate. thanks for that.  i will update the script now. and test, and give you some feedback when i get that error again mate

**Comment by Man12340** [comment]
so i now see this ```on 927: Exception processing "Criminal Confessions": (404) not_found; https://plex.mydomain.co.uk/library/metadata/378230/posters 404 page not found
on 928: Exception processing "Criminal Minds": (404) not_found; https://plex.mydomain.co.uk/library/metadata/213477/posters 404 page not found
on 929: Exception processing "Criminal Minds: Beyond Borders": (404) not_found; https://plex.mydomain.co.uk/library/metadata/441426/posters 404 page not found
on 930: Exception processing "Criminal Minds: Suspect Behavior": (404) not_found; https://plex.mydomain.co.uk/library/metadata/441831/posters 404 page not found
on 931: Exception processing "Criminal: United Kingdom": (404) not_found; https://plex.mydomain.co.uk/library/metadata/452496/posters 404 page not found```
so i now this means there was no poster for that in the1st place.

**Comment by chazlarson** [comment]
The script is asking Plex [via the Plex API library]  for the list of posters it has for an item, and the plex server is returning a 404. This is not normal; if it has no posters available it should return an empty list.

Are these things unmatched in Plex or something?

**Comment by Man12340** [comment]
that shows was matched in plex. so i had no idea. i did re-run it  since then. and the only other error is ```on 2228: Exception processing "I Dream of Jeannie": HTTPSConnectionPool(host='plex.mydomain.co.uk', port=443): Read timed out. (read timeout=30)
```
which i assume this means.it failed to connect to plex at the time.

**Comment by chazlarson** [comment]
Yep, that's a timeout connecting to Plex.

**Comment by chazlarson** [comment]
I've made some changes that let you set a global plex timeout to help with these.
